In [1]:
import torch
import numpy as np

`Tensor（张量）`是PyTorch的核心数据元素。张量在不同学科中有不同的意义，在深度学习中张量表示一个多维数组，是标量、向量、矩阵的扩展。如一个RGB图像的数组就是一个三维张量，第1维是图像的高，第2维是图像的宽，第3维是图像的颜色通道。

# 基本张量的创建

## 创建指定内容的张量

In [2]:
tensor1 = torch.tensor(10)  # 传入一个标量来创建张量
print(tensor1)
print(tensor1.size())  # size()表示张量的维度，0维即标量
print(tensor1.dtype)  # dtype属性表示张量类型

tensor(10)
torch.Size([])
torch.int64


In [3]:
tensor2 = torch.tensor([1., 2, 3])  # 传入一个数组来创建张量
print(tensor2)
print(tensor2.size())  # size()表示张量的维度，0维即标量
print(tensor2.dtype)  # dtype属性表示张量类型

tensor([1., 2., 3.])
torch.Size([3])
torch.float32


In [4]:
tensor3 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))  # 传入一个numpy数组来创建张量
print(tensor3)
print(tensor3.size())  # size()表示张量的维度，0维即标量
print(tensor3.dtype)  # dtype属性表示张量类型

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


## 创建指定形状的张量

In [5]:
tensor1 = torch.Tensor(3, 2, 4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)  # 默认 float32

tensor([[[1.0059e+28, 1.0678e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [6]:
tensor2 = torch.Tensor([[1, 2, 3, 4], [4, 5, 6, 7]])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)  # 通过 Tensor指定元素创建张量，也会将类型转化为float32

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


In [7]:
tensor3 = torch.Tensor(np.array([[1, 2, 3, 4], [4, 5, 6, 7]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


In [8]:
tensor1 = torch.Tensor(10)  # 通过 Tensor(标量) 来创建张量，会生成维度为“标量”的张量，区别 tensor(标量)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
torch.float32


## 创建指定类型的张量

In [9]:
# 创建整数类型
# int32
tensor1 = torch.IntTensor(2, 3)  # 类似对 torch.Tensor()进行扩展，在函数前添加张量类型，数据类型类似C语言
tensor2 = torch.tensor([2, 3, 4], dtype=torch.int32)
print(tensor1.dtype)
print(tensor2.dtype)

# int64
tensor1 = torch.LongTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

# int16
tensor1 = torch.ShortTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.int16)
print(tensor1.dtype)
print(tensor2.dtype)

# char
tensor1 = torch.CharTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.uint8)
print(tensor1.dtype)
print(tensor2.dtype)

# float
tensor1 = torch.FloatTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.float32)
print(tensor1.dtype)
print(tensor2.dtype)

# double
tensor1 = torch.DoubleTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)

# 半精度浮点数
tensor1 = torch.HalfTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.float16)
print(tensor1.dtype)
print(tensor2.dtype)

# bool
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int32
torch.int32
torch.int64
torch.int64
torch.int16
torch.int16
torch.int8
torch.uint8
torch.float32
torch.float32
torch.float64
torch.float64
torch.float16
torch.float16
torch.bool
torch.bool


## 创建指定区间的张量

In [10]:
tensor1 = torch.arange(10, 30, 2)  # 左闭右开
print(tensor1)

tensor2 = torch.linspace(10, 30, 4)  # 左闭右闭，在start和end中间均匀分布n个元素
print(tensor2)

tensor3 = torch.logspace(1, 5, 3, base=2)  # 左闭右闭，在start和end中生成指数空间
print(tensor3)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
tensor([10.0000, 16.6667, 23.3333, 30.0000])
tensor([ 2.,  8., 32.])


## 创建指定数值扩充的张量

In [11]:
tensor1 = torch.zeros(10)
print(tensor1)
tensor1 = torch.ones(10)
print(tensor1)
tensor1 = torch.full((3, 2), 6)
print(tensor1)
tensor1 = torch.empty(10)  # 指定创建形状，未初始化的张量
print(tensor1)

tensor1 = torch.Tensor(3, 2)
tensor1 = torch.zeros_like(tensor1)
print(tensor1)
tensor1 = torch.ones_like(tensor1)
print(tensor1)
tensor1 = torch.full_like(tensor1, 3)
print(tensor1)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[6, 6],
        [6, 6],
        [6, 6]])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [12]:
# 创建单位矩阵
tensor1 = torch.eye(4, 5)
print(tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])


## 创建随机数值的方法

In [13]:
tensor1 = torch.rand(2, 3)  # 在[0, 1)均匀分布，指定形状的张量
print(tensor1)
tensor1 = torch.randint(3, 100, (5, 6))  # 在[low, high)均匀分布，指定形状的张量
print(tensor1)
tensor1 = torch.randn(3, 2)  # 标准正态分布
print(tensor1)
tensor1 = torch.normal(0, 1, (3, 4))
print(tensor1)
tensor1 = torch.rand_like(tensor1)
print(tensor1)
tensor1 = torch.randint_like(tensor1, low=5, high=20)
print(tensor1)

tensor([[0.0419, 0.0346, 0.3784],
        [0.6433, 0.5710, 0.3147]])
tensor([[99, 56, 34, 66, 52, 41],
        [37, 99,  4, 58, 45, 72],
        [62, 20, 21, 45, 37, 62],
        [24, 65, 49, 55, 76, 84],
        [14, 80, 85,  8, 75, 32]])
tensor([[-0.4630, -0.1930],
        [-0.9410,  0.5406],
        [-0.1339, -0.7201]])
tensor([[-0.9369, -0.0631, -1.9798,  2.5518],
        [ 0.2161,  0.0327,  0.0765,  1.5750],
        [ 1.1201,  0.9893, -2.3301,  0.2848]])
tensor([[0.2526, 0.9167, 0.6146, 0.1300],
        [0.5250, 0.2783, 0.6807, 0.4151],
        [0.7709, 0.2340, 0.4306, 0.8701]])
tensor([[11., 14.,  8., 12.],
        [17.,  8.,  5., 15.],
        [19., 12., 15.,  5.]])


In [14]:
tensor1 = torch.randperm(10)  # 随机重排，类似洗牌操作
print(tensor1)

print(torch.random.initial_seed())  # 获取随机种子
torch.random.manual_seed(1)  #设置随机种子

tensor([4, 2, 5, 6, 1, 3, 9, 0, 7, 8])
131528226000
