In [2]:
import torch
import numpy as np

`Tensor（张量）`是PyTorch的核心数据元素。张量在不同学科中有不同的意义，在深度学习中张量表示一个多维数组，是标量、向量、矩阵的扩展。如一个RGB图像的数组就是一个三维张量，第1维是图像的高，第2维是图像的宽，第3维是图像的颜色通道。

# 基本张量的创建

## 创建指定内容的张量

In [3]:
tensor1 = torch.tensor(10)  # 传入一个标量来创建张量
print(tensor1)
print(tensor1.size())  # size()表示张量的维度，0维即标量
print(tensor1.dtype)  # dtype属性表示张量类型

tensor(10)
torch.Size([])
torch.int64


In [11]:
tensor2 = torch.tensor([1., 2, 3])  # 传入一个数组来创建张量
print(tensor2)
print(tensor2.size())  # size()表示张量的维度，0维即标量
print(tensor2.dtype)  # dtype属性表示张量类型

tensor([1., 2., 3.])
torch.Size([3])
torch.float32


In [14]:
tensor3 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))  # 传入一个numpy数组来创建张量
print(tensor3)
print(tensor3.size())  # size()表示张量的维度，0维即标量
print(tensor3.dtype)  # dtype属性表示张量类型

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


## 创建指定形状的张量

In [17]:
tensor1 = torch.Tensor(3, 2, 4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)  # 默认 float32

tensor([[[1.7626e-18, 1.7811e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [20]:
tensor2 = torch.Tensor([[1, 2, 3, 4], [4, 5, 6, 7]])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)  # 通过 Tensor指定元素创建张量，也会将类型转化为float32

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


In [19]:
tensor3 = torch.Tensor(np.array([[1, 2, 3, 4], [4, 5, 6, 7]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
torch.float32


In [21]:
tensor1 = torch.Tensor(10)  # 通过 Tensor(标量) 来创建张量，会生成维度为“标量”的张量，区别 tensor(标量)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
torch.float32


## 创建指定类型的张量

In [31]:
# 创建整数类型
# int32
tensor1 = torch.IntTensor(2, 3)  # 类似对 torch.Tensor()进行扩展，在函数前添加张量类型，数据类型类似C语言
tensor2 = torch.tensor([2, 3, 4], dtype=torch.int32)
print(tensor1.dtype)
print(tensor2.dtype)

# int64
tensor1 = torch.LongTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

# int16
tensor1 = torch.ShortTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.int16)
print(tensor1.dtype)
print(tensor2.dtype)

# char
tensor1 = torch.CharTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.uint8)
print(tensor1.dtype)
print(tensor2.dtype)

# float
tensor1 = torch.FloatTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.float32)
print(tensor1.dtype)
print(tensor2.dtype)

# double
tensor1 = torch.DoubleTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)

# 半精度浮点数
tensor1 = torch.HalfTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.float16)
print(tensor1.dtype)
print(tensor2.dtype)

# bool
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([2, 3, 4], dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int32
torch.int32
torch.int64
torch.int64
torch.int16
torch.int16
torch.int8
torch.uint8
torch.float32
torch.float32
torch.float64
torch.float64
torch.float16
torch.float16
torch.bool
torch.bool


## 创建指定区间的张量

In [48]:
tensor1 = torch.arange(10, 30, 2)  # 左闭右开
print(tensor1)

tensor2 = torch.linspace(10, 30, 4)  # 左闭右闭，在start和end中间均匀分布n个元素
print(tensor2)

tensor3 = torch.logspace(1, 5, 3, base=2)  # 左闭右闭，在start和end中生成指数空间
print(tensor3)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
tensor([10.0000, 16.6667, 23.3333, 30.0000])
tensor([ 2.,  8., 32.])


## 创建指定数值扩充的张量

In [59]:
tensor1 = torch.zeros(10)
print(tensor1)
tensor1 = torch.ones(10)
print(tensor1)
tensor1 = torch.full((3, 2), 6)
print(tensor1)
tensor1 = torch.empty(10)  # 指定创建形状，未初始化的张量
print(tensor1)

tensor1 = torch.Tensor(3, 2)
tensor1 = torch.zeros_like(tensor1)
print(tensor1)
tensor1 = torch.ones_like(tensor1)
print(tensor1)
tensor1 = torch.full_like(tensor1, 3)
print(tensor1)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[6, 6],
        [6, 6],
        [6, 6]])
tensor([1.7756e-18, 1.7811e-42, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [62]:
# 创建单位矩阵
tensor1 = torch.eye(4, 5)
print(tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])


## 创建随机数值的方法

In [90]:
tensor1 = torch.rand(2, 3)  # 在[0, 1)均匀分布，指定形状的张量
print(tensor1)
tensor1 = torch.randint(3, 100, (5, 6))  # 在[low, high)均匀分布，指定形状的张量
print(tensor1)
tensor1 = torch.randn(3, 2)  # 标准正态分布
print(tensor1)
tensor1 = torch.normal(0, 1, (3, 4))
print(tensor1)
tensor1 = torch.rand_like(tensor1)
print(tensor1)
tensor1 = torch.randint_like(tensor1, low=5, high=20)
print(tensor1)

tensor([[0.9952, 0.8126, 0.0173],
        [0.2498, 0.7943, 0.2151]])
tensor([[42, 85, 97, 56, 19, 93],
        [80, 24,  5, 16, 98, 30],
        [93, 89, 71, 81, 18,  7],
        [68, 27, 60, 68, 19, 59],
        [82, 15, 67, 15, 57, 98]])
tensor([[-0.6315, -0.1127],
        [-0.5245, -2.3073],
        [ 0.0894, -1.3097]])
tensor([[ 0.2789,  0.7887, -0.0715,  0.9432],
        [-1.5687, -0.1340, -0.4120, -1.3874],
        [-2.0165, -1.3474,  0.0029, -1.5218]])
tensor([[0.8020, 0.5688, 0.7687, 0.4929],
        [0.6025, 0.7769, 0.1946, 0.6554],
        [0.4719, 0.5849, 0.9972, 0.9351]])
tensor([[17., 12.,  8., 17.],
        [13., 17.,  9.,  7.],
        [14., 19.,  7., 16.]])


In [94]:
tensor1 = torch.randperm(10)  # 随机重排，类似洗牌操作
print(tensor1)

print(torch.random.initial_seed())  # 获取随机种子
torch.random.manual_seed(1)  #设置随机种子

tensor([5, 6, 1, 2, 0, 8, 9, 3, 7, 4])
1
