In [9]:
import torch
import numpy as np

# 张量转换

## 张量元素类型转换


In [10]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1.dtype)

tensor1 = tensor1.type(torch.float32)
print(tensor1.dtype)
print(tensor1)

torch.int64
torch.float32
tensor([1., 2., 3.])


In [11]:
tensor1 = tensor1.double()
print(tensor1.dtype)

# 转化为复数
tensor1 = tensor1.to(torch.complex64)
print(tensor1, tensor1.dtype)

torch.float64
tensor([1.+0.j, 2.+0.j, 3.+0.j]) torch.complex64


## Tensor与ndarray之间的转换

In [12]:
np.set_printoptions(precision=6)  # 统一输出六位小数
torch.set_printoptions(precision=6)
# Tensor.numpy()将Tensor转化为ndarray，共享内存，使用copy()避免共享内存
tensor1 = torch.rand(3, 2)
numpy_array1 = tensor1.numpy()
numpy_array2 = tensor1.numpy().copy()

print(tensor1)
print(numpy_array1)

# 修改其中某一项
tensor1[:, 0] = 10
print(tensor1)
print(numpy_array1)
print(numpy_array2)

# 使用copy()方法避免共享内存

tensor([[0.110921, 0.945342],
        [0.608282, 0.864809],
        [0.959864, 0.390394]])
[[0.110921 0.945342]
 [0.608282 0.864809]
 [0.959864 0.390394]]
tensor([[10.000000,  0.945342],
        [10.000000,  0.864809],
        [10.000000,  0.390394]])
[[10.        0.945342]
 [10.        0.864809]
 [10.        0.390394]]
[[0.110921 0.945342]
 [0.608282 0.864809]
 [0.959864 0.390394]]


In [13]:
numpy_array1 = np.random.randn(3, 2)
tensor1 = torch.from_numpy(numpy_array1)
tensor2 = torch.from_numpy(numpy_array1.copy())  # 使用copy()避免内存共享

print(tensor1)
print(numpy_array1)

numpy_array1[:, 0] = 5
print(tensor1)
print(tensor2)
print(numpy_array1)

tensor([[-2.009913,  0.403764],
        [-1.554732,  0.271029],
        [ 1.226320,  0.200494]], dtype=torch.float64)
[[-2.009913  0.403764]
 [-1.554732  0.271029]
 [ 1.22632   0.200494]]
tensor([[5.000000, 0.403764],
        [5.000000, 0.271029],
        [5.000000, 0.200494]], dtype=torch.float64)
tensor([[-2.009913,  0.403764],
        [-1.554732,  0.271029],
        [ 1.226320,  0.200494]], dtype=torch.float64)
[[5.       0.403764]
 [5.       0.271029]
 [5.       0.200494]]


In [14]:
# 通过ndarray创建张量，不会共享内存，更为方便
tensor1 = torch.tensor(numpy_array1)
numpy_array1[:, 0] = 100
print(tensor1)
print(numpy_array1)

tensor([[5.000000, 0.403764],
        [5.000000, 0.271029],
        [5.000000, 0.200494]], dtype=torch.float64)
[[100.         0.403764]
 [100.         0.271029]
 [100.         0.200494]]


## Tensor与标量之间的转换

In [15]:
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [16]:
tensor1 = torch.tensor(10)
print(tensor1.item())

## Tensor与标量之间的转换
tensor1 = torch.tensor([20])
print(tensor1.item())

tensor1 = torch.tensor([[30]])
print(tensor1.item())  # 只要张量中只有一个元素，就可以使用item()方法提取为标量

10
20
30
