In [1]:
import torch
import numpy as np
from numpy import ndarray

# 张量转换

## 张量元素类型转换


In [2]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1.dtype)

tensor1 = tensor1.type(torch.float32)
print(tensor1.dtype)

torch.int64
torch.float32


In [6]:
tensor1 = tensor1.double()
print(tensor1.dtype)

# 转化为复数
tensor1 = tensor1.to(torch.complex64)
print(tensor1, tensor1.dtype)

torch.float64
tensor([1.+0.j, 2.+0.j, 3.+0.j]) torch.complex64


## Tensor与ndarray之间的转换

In [14]:
np.set_printoptions(precision=6)  # 统一输出六位小数
torch.set_printoptions(precision=6)
# Tensor.numpy()将Tensor转化为ndarray，共享内存，使用copy()避免共享内存
tensor1 = torch.rand(3, 2)
numpy_array1 = tensor1.numpy()
numpy_array2 = tensor1.numpy().copy()

print(tensor1)
print(numpy_array1)

# 修改其中某一项
tensor1[:, 0] = 10
print(tensor1)
print(numpy_array1)
print(numpy_array2)

# 使用copy()方法避免共享内存

tensor([[0.961790, 0.710681],
        [0.924934, 0.805251],
        [0.055758, 0.884523]])
[[0.96179  0.710681]
 [0.924934 0.805251]
 [0.055758 0.884523]]
tensor([[10.000000,  0.710681],
        [10.000000,  0.805251],
        [10.000000,  0.884523]])
[[10.        0.710681]
 [10.        0.805251]
 [10.        0.884523]]
[[0.96179  0.710681]
 [0.924934 0.805251]
 [0.055758 0.884523]]


In [19]:
numpy_array1 = np.random.randn(3, 2)
tensor1 = torch.from_numpy(numpy_array1)
tensor2 = torch.from_numpy(numpy_array1.copy())  # 使用copy()避免内存共享

print(tensor1)
print(numpy_array1)

numpy_array1[:, 0] = 5
print(tensor1)
print(tensor2)
print(numpy_array1)

tensor([[-1.075414, -0.888388],
        [-0.599528,  1.377241],
        [-0.652946,  1.219704]], dtype=torch.float64)
[[-1.075414 -0.888388]
 [-0.599528  1.377241]
 [-0.652946  1.219704]]
tensor([[ 5.000000, -0.888388],
        [ 5.000000,  1.377241],
        [ 5.000000,  1.219704]], dtype=torch.float64)
tensor([[-1.075414, -0.888388],
        [-0.599528,  1.377241],
        [-0.652946,  1.219704]], dtype=torch.float64)
[[ 5.       -0.888388]
 [ 5.        1.377241]
 [ 5.        1.219704]]


In [20]:
# 通过ndarray创建张量，不会共享内存，更为方便
tensor1 = torch.tensor(numpy_array1)
numpy_array1[:, 0] = 100
print(tensor1)
print(numpy_array1)

tensor([[ 5.000000, -0.888388],
        [ 5.000000,  1.377241],
        [ 5.000000,  1.219704]], dtype=torch.float64)
[[100.        -0.888388]
 [100.         1.377241]
 [100.         1.219704]]


## Tensor与标量之间的转换

In [23]:
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [28]:
tensor1 = torch.tensor(10)
print(tensor1.item())

## Tensor与标量之间的转换
tensor1 = torch.tensor([20])
print(tensor1.item())

tensor1 = torch.tensor([[30]])
print(tensor1.item())  # 只要张量中只有一个元素，就可以使用item()方法提取为标量

10
20
30
