In [1]:
import torch

# 张量的运算

In [14]:
tensor1 = torch.randint(low=0, high=10, size=(2, 3))
print(tensor1)

tensor([[6, 3, 7],
        [3, 2, 1]])


In [15]:
print(tensor1 + 10)
print(tensor1)

tensor([[16, 13, 17],
        [13, 12, 11]])
tensor([[6, 3, 7],
        [3, 2, 1]])


In [16]:
print(tensor1.add(10))  # add()方法并不会修改原张量中的值
print(tensor1)

tensor([[16, 13, 17],
        [13, 12, 11]])
tensor([[6, 3, 7],
        [3, 2, 1]])


In [17]:
print(tensor1.add_(10))  # add_()方法会修改原张量中的值，同理，sub() multi() div() neg() 相同
print(tensor1)

tensor([[16, 13, 17],
        [13, 12, 11]])
tensor([[16, 13, 17],
        [13, 12, 11]])


In [18]:
print(tensor1.sub(10).pow(3))  # pow_()方法会修改原张量中的值

print(tensor1.pow_(2))
print(tensor1.sqrt())

tensor([[216,  27, 343],
        [ 27,   8,   1]])
tensor([[256, 169, 289],
        [169, 144, 121]])
tensor([[16., 13., 17.],
        [13., 12., 11.]])


In [20]:
# 哈达玛积
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor1 * tensor2)
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [23]:
# 二维矩阵乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
# mm()严格用于二维矩阵乘法
print(tensor1.mm(tensor2))
# @ matmul()支持多维矩阵，按最后两个维度做矩阵乘法，其他维度相同，或者至少为1个张量维度为1，广播后进行运算
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
