In [1]:
import torch

# 张量的运算

In [2]:
tensor1 = torch.randint(low=0, high=10, size=(2, 3))
print(tensor1)

tensor([[4, 2, 4],
        [6, 7, 2]])


In [3]:
print(tensor1 + 10)
print(tensor1)

tensor([[14, 12, 14],
        [16, 17, 12]])
tensor([[4, 2, 4],
        [6, 7, 2]])


In [4]:
print(tensor1.add(10))  # add()方法并不会修改原张量中的值
print(tensor1)

tensor([[14, 12, 14],
        [16, 17, 12]])
tensor([[4, 2, 4],
        [6, 7, 2]])


In [5]:
print(tensor1.add_(10))  # add_()方法会修改原张量中的值，同理，sub() multi() div() neg() 相同
print(tensor1)

tensor([[14, 12, 14],
        [16, 17, 12]])
tensor([[14, 12, 14],
        [16, 17, 12]])


In [6]:
print(tensor1.sub(10).pow(3))  # pow_()方法会修改原张量中的值

print(tensor1.pow_(2))
print(tensor1.sqrt())

tensor([[ 64,   8,  64],
        [216, 343,   8]])
tensor([[196, 144, 196],
        [256, 289, 144]])
tensor([[14., 12., 14.],
        [16., 17., 12.]])


In [7]:
# 哈达玛积
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor1 * tensor2)
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [8]:
# 二维矩阵乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
# mm()严格用于二维矩阵乘法
print(tensor1.mm(tensor2))
# @ matmul()支持多维矩阵，按最后两个维度做矩阵乘法，其他维度相同，或者至少为1个张量维度为1，广播后进行运算
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])


In [9]:
# 验证内存共享和节省内存
X = torch.randint(1, 10, (3, 2, 4))
print(X)
print(id(X))

# X = X + 10
X += 10  # 节省内存
print(id(X))

tensor([[[3, 5, 2, 5],
         [1, 2, 1, 7]],

        [[6, 4, 6, 1],
         [3, 8, 5, 6]],

        [[6, 3, 2, 4],
         [6, 9, 5, 5]]])
2383147140592
2383147140592


In [10]:
X = torch.randint(1, 10, (3, 2, 4))
Y = torch.randint(1, 10, (3, 4, 1))
print('X:\t', X)
print('Y:\t', Y)
print('X @ Y:\t', X @ Y)
print(X.shape)
print(id(X))
# X = X @ Y
# X @= Y  # 通过 @= 运算仍然无法原地运算 -> X的形状发生改变
X[:] = X @ Y  # 形状不一致就应该开辟新的空间进行存储，除非某一个维度为1，进行广播
print(X.shape)
print('X:\t', X)
print(id(X))

X:	 tensor([[[7, 4, 7, 3],
         [8, 2, 2, 9]],

        [[6, 9, 3, 2],
         [4, 5, 8, 4]],

        [[9, 6, 9, 1],
         [5, 1, 6, 1]]])
Y:	 tensor([[[5],
         [6],
         [1],
         [1]],

        [[7],
         [8],
         [5],
         [9]],

        [[5],
         [5],
         [1],
         [1]]])
X @ Y:	 tensor([[[ 69],
         [ 63]],

        [[147],
         [144]],

        [[ 85],
         [ 37]]])
torch.Size([3, 2, 4])
2381669177040
torch.Size([3, 2, 4])
X:	 tensor([[[ 69,  69,  69,  69],
         [ 63,  63,  63,  63]],

        [[147, 147, 147, 147],
         [144, 144, 144, 144]],

        [[ 85,  85,  85,  85],
         [ 37,  37,  37,  37]]])
2381669177040
