In [2]:
import torch

# 张量的运算

In [14]:
tensor1 = torch.randint(low=0, high=10, size=(2, 3))
print(tensor1)

tensor([[6, 3, 7],
        [3, 2, 1]])


In [15]:
print(tensor1 + 10)
print(tensor1)

tensor([[16, 13, 17],
        [13, 12, 11]])
tensor([[6, 3, 7],
        [3, 2, 1]])


In [16]:
print(tensor1.add(10))  # add()方法并不会修改原张量中的值
print(tensor1)

tensor([[16, 13, 17],
        [13, 12, 11]])
tensor([[6, 3, 7],
        [3, 2, 1]])


In [17]:
print(tensor1.add_(10))  # add_()方法会修改原张量中的值，同理，sub() multi() div() neg() 相同
print(tensor1)

tensor([[16, 13, 17],
        [13, 12, 11]])
tensor([[16, 13, 17],
        [13, 12, 11]])


In [18]:
print(tensor1.sub(10).pow(3))  # pow_()方法会修改原张量中的值

print(tensor1.pow_(2))
print(tensor1.sqrt())

tensor([[216,  27, 343],
        [ 27,   8,   1]])
tensor([[256, 169, 289],
        [169, 144, 121]])
tensor([[16., 13., 17.],
        [13., 12., 11.]])


In [20]:
# 哈达玛积
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor1 * tensor2)
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [23]:
# 二维矩阵乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
# mm()严格用于二维矩阵乘法
print(tensor1.mm(tensor2))
# @ matmul()支持多维矩阵，按最后两个维度做矩阵乘法，其他维度相同，或者至少为1个张量维度为1，广播后进行运算
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])


In [7]:
# 验证内存共享和节省内存
X = torch.randint(1, 10, (3, 2, 4))
print(X)
print(id(X))

# X = X + 10
X += 10  # 节省内存
print(id(X))

tensor([[[2, 6, 4, 1],
         [9, 2, 5, 2]],

        [[4, 8, 5, 3],
         [5, 5, 7, 6]],

        [[8, 2, 3, 9],
         [2, 1, 4, 7]]])
2604797232064
2604797232064


In [18]:
X = torch.randint(1, 10, (3, 2, 4))
Y = torch.randint(1, 10, (3, 4, 1))
print('X:\t', X)
print('Y:\t', Y)
print('X @ Y:\t', X @ Y)
print(X.shape)
print(id(X))
# X = X @ Y
# X @= Y  # 通过 @= 运算仍然无法原地运算 -> X的形状发生改变
X[:] = X @ Y  # 形状不一致就应该开辟新的空间进行存储，除非某一个维度为1，进行广播
print(X.shape)
print('X:\t', X)
print(id(X))

X:	 tensor([[[8, 7, 4, 6],
         [5, 5, 1, 4]],

        [[3, 7, 6, 1],
         [6, 3, 8, 6]],

        [[5, 2, 4, 8],
         [1, 8, 8, 9]]])
Y:	 tensor([[[4],
         [1],
         [7],
         [3]],

        [[8],
         [8],
         [1],
         [7]],

        [[7],
         [5],
         [9],
         [8]]])
X @ Y:	 tensor([[[ 85],
         [ 44]],

        [[ 93],
         [122]],

        [[145],
         [191]]])
torch.Size([3, 2, 4])
2604797417168
torch.Size([3, 2, 4])
X:	 tensor([[[ 85,  85,  85,  85],
         [ 44,  44,  44,  44]],

        [[ 93,  93,  93,  93],
         [122, 122, 122, 122]],

        [[145, 145, 145, 145],
         [191, 191, 191, 191]]])
2604797417168
