# 张量统计相关

In [1]:
import torch

In [5]:
tensor1 = torch.randint(1, 10, (3, 2, 4)).float()
print(tensor1)

tensor([[[7., 3., 6., 7.],
         [3., 8., 2., 8.]],

        [[6., 3., 3., 5.],
         [9., 1., 4., 8.]],

        [[5., 1., 5., 2.],
         [5., 2., 4., 3.]]])


In [6]:
# sum 求和
print(tensor1.sum())
print(tensor1.sum(dim=0))  # 降第0维
print(tensor1.sum(dim=1))
print(tensor1.sum(dim=2))

tensor(110.)
tensor([[18.,  7., 14., 14.],
        [17., 11., 10., 19.]])
tensor([[10., 11.,  8., 15.],
        [15.,  4.,  7., 13.],
        [10.,  3.,  9.,  5.]])
tensor([[23., 21.],
        [17., 22.],
        [13., 14.]])


In [8]:
# mean 求均值，要求数据类型必须为float型或者Complex型
print(tensor1.mean())
print(tensor1.mean(dim=2))

tensor(4.5833)
tensor([[5.7500, 5.2500],
        [4.2500, 5.5000],
        [3.2500, 3.5000]])


In [10]:
# std 求标准方差
print(tensor1.std())
print(tensor1.std(dim=2))

tensor(2.3759)
tensor([[1.8930, 3.2016],
        [1.5000, 3.6968],
        [2.0616, 1.2910]])


In [16]:
# max min 求最大最小值
print(tensor1.max())
print(tensor1.max(dim=2))  # 指定维度，可以同时获取该维度最值和其对应的索引
print(tensor1.min())
print(tensor1.min(dim=2))

print(tensor1.argmin())

tensor(9.)
torch.return_types.max(
values=tensor([[7., 8.],
        [6., 9.],
        [5., 5.]]),
indices=tensor([[0, 1],
        [0, 0],
        [0, 0]]))
tensor(1.)
torch.return_types.min(
values=tensor([[3., 2.],
        [3., 1.],
        [1., 2.]]),
indices=tensor([[1, 2],
        [1, 1],
        [1, 1]]))
tensor(13)


In [19]:
# unique 去重
print(tensor1.unique())  # 得到一维张量
print(tensor1.unique(dim = 2))

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[[3., 6., 7., 7.],
         [8., 2., 3., 8.]],

        [[3., 3., 6., 5.],
         [1., 4., 9., 8.]],

        [[1., 5., 5., 2.],
         [2., 4., 5., 3.]]])


In [22]:
# sort 排序
print(tensor1.sort())   # 在这里默认 dim=2

torch.return_types.sort(
values=tensor([[[3., 6., 7., 7.],
         [2., 3., 8., 8.]],

        [[3., 3., 5., 6.],
         [1., 4., 8., 9.]],

        [[1., 2., 5., 5.],
         [2., 3., 4., 5.]]]),
indices=tensor([[[1, 2, 0, 3],
         [2, 0, 1, 3]],

        [[1, 2, 3, 0],
         [1, 2, 3, 0]],

        [[1, 3, 0, 2],
         [1, 3, 2, 0]]]))
