In [1]:
import torch

# 张量统计相关

In [2]:
tensor1 = torch.randint(1, 10, (3, 2, 4)).float()
print(tensor1)

tensor([[[4., 6., 2., 6.],
         [4., 2., 8., 4.]],

        [[1., 7., 9., 2.],
         [4., 3., 6., 5.]],

        [[6., 4., 8., 5.],
         [9., 8., 5., 4.]]])


In [3]:
# sum 求和
print(tensor1.sum())
print(tensor1.sum(dim=0))  # 降第0维
print(tensor1.sum(dim=1))
print(tensor1.sum(dim=2))

tensor(122.)
tensor([[11., 17., 19., 13.],
        [17., 13., 19., 13.]])
tensor([[ 8.,  8., 10., 10.],
        [ 5., 10., 15.,  7.],
        [15., 12., 13.,  9.]])
tensor([[18., 18.],
        [19., 18.],
        [23., 26.]])


In [4]:
# mean 求均值，要求数据类型必须为float型或者Complex型
print(tensor1.mean())
print(tensor1.mean(dim=2))

tensor(5.0833)
tensor([[4.5000, 4.5000],
        [4.7500, 4.5000],
        [5.7500, 6.5000]])


In [5]:
# std 求标准方差
print(tensor1.std())
print(tensor1.std(dim=2))

tensor(2.2826)
tensor([[1.9149, 2.5166],
        [3.8622, 1.2910],
        [1.7078, 2.3805]])


In [6]:
# max min 求最大最小值
print(tensor1.max())
print(tensor1.max(dim=2))  # 指定维度，可以同时获取该维度最值和其对应的索引
print(tensor1.min())
print(tensor1.min(dim=2))

print(tensor1.argmin())

tensor(9.)
torch.return_types.max(
values=tensor([[6., 8.],
        [9., 6.],
        [8., 9.]]),
indices=tensor([[1, 2],
        [2, 2],
        [2, 0]]))
tensor(1.)
torch.return_types.min(
values=tensor([[2., 2.],
        [1., 3.],
        [4., 4.]]),
indices=tensor([[2, 1],
        [0, 1],
        [1, 3]]))
tensor(8)


In [7]:
# unique 去重
print(tensor1.unique())  # 得到一维张量
print(tensor1.unique(dim = 2))

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[[2., 4., 6., 6.],
         [8., 4., 2., 4.]],

        [[9., 1., 7., 2.],
         [6., 4., 3., 5.]],

        [[8., 6., 4., 5.],
         [5., 9., 8., 4.]]])


In [8]:
# sort 排序
print(tensor1.sort())   # 在这里默认 dim=2

torch.return_types.sort(
values=tensor([[[2., 4., 6., 6.],
         [2., 4., 4., 8.]],

        [[1., 2., 7., 9.],
         [3., 4., 5., 6.]],

        [[4., 5., 6., 8.],
         [4., 5., 8., 9.]]]),
indices=tensor([[[2, 0, 1, 3],
         [1, 0, 3, 2]],

        [[0, 3, 1, 2],
         [1, 0, 3, 2]],

        [[1, 3, 0, 2],
         [3, 2, 1, 0]]]))
