In [1]:
import torch

# 张量索引相关

In [3]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

tensor([[[4, 9, 2, 3],
         [8, 9, 3, 7],
         [7, 7, 8, 3],
         [6, 2, 2, 1],
         [8, 8, 5, 3]],

        [[6, 8, 4, 3],
         [1, 9, 7, 2],
         [6, 7, 2, 4],
         [4, 9, 4, 3],
         [5, 1, 6, 4]],

        [[3, 6, 5, 6],
         [4, 8, 2, 4],
         [3, 8, 9, 2],
         [1, 5, 5, 9],
         [8, 3, 3, 3]]])


In [7]:
# 简单索引
print(tensor1[2, 1, 3])
print(tensor1[2, 3])

tensor(4)
tensor([1, 5, 5, 9])
tensor([[6, 2, 2, 1],
        [4, 9, 4, 3],
        [1, 5, 5, 9]])


In [11]:
# 范围索引
print(tensor1[:, 3])
print(tensor1[1:])
print(tensor1[:, 2:4, 3])

tensor([[6, 2, 2, 1],
        [4, 9, 4, 3],
        [1, 5, 5, 9]])
tensor([[[6, 8, 4, 3],
         [1, 9, 7, 2],
         [6, 7, 2, 4],
         [4, 9, 4, 3],
         [5, 1, 6, 4]],

        [[3, 6, 5, 6],
         [4, 8, 2, 4],
         [3, 8, 9, 2],
         [1, 5, 5, 9],
         [8, 3, 3, 3]]])
tensor([[3, 1],
        [4, 3],
        [2, 9]])


In [15]:
# 列表索引
print(tensor1[[0, 1], [1, 2], [1, 3]])  # 所选取的元素坐标
print(tensor1[[[0], [1]], [1, 2]])  # 一对多的关系

tensor([9, 4])
tensor([[[8, 9, 3, 7],
         [7, 7, 8, 3]],

        [[1, 9, 7, 2],
         [6, 7, 2, 4]]])


In [18]:
# 布尔索引
mask = tensor1[:, :, 0] > 5  # 判断每行首元素是否大于5
print(mask)
print(tensor1[mask])

tensor([[False,  True,  True,  True,  True],
        [ True, False,  True, False, False],
        [False, False, False, False,  True]])
tensor([[8, 9, 3, 7],
        [7, 7, 8, 3],
        [6, 2, 2, 1],
        [8, 8, 5, 3],
        [6, 8, 4, 3],
        [6, 7, 2, 4],
        [8, 3, 3, 3]])


In [35]:
mask = tensor1[:, 1, :] > 5  # 判断每列第二个元素是否大于5
print(mask)
tensor2 = tensor1.permute(0, 2, 1)  # permute：一般化的转置
print(tensor2[mask])

tensor([[ True,  True, False,  True],
        [False,  True,  True, False],
        [False,  True, False, False]])
tensor([[4, 8, 7, 6, 8],
        [9, 9, 7, 2, 8],
        [3, 7, 3, 1, 3],
        [8, 9, 7, 9, 1],
        [4, 7, 2, 4, 6],
        [6, 8, 8, 5, 3]])


In [38]:
# 选取符合条件的矩阵
mask = tensor1[:, 0, 1] > 7
print(mask)
print(tensor1[mask])

tensor([ True,  True, False])
tensor([[[4, 9, 2, 3],
         [8, 9, 3, 7],
         [7, 7, 8, 3],
         [6, 2, 2, 1],
         [8, 8, 5, 3]],

        [[6, 8, 4, 3],
         [1, 9, 7, 2],
         [6, 7, 2, 4],
         [4, 9, 4, 3],
         [5, 1, 6, 4]]])
