In [1]:
import torch

# 张量索引相关

In [2]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

tensor([[[1, 9, 9, 7],
         [8, 7, 4, 1],
         [8, 3, 1, 2],
         [5, 6, 3, 3],
         [4, 8, 8, 5]],

        [[1, 4, 8, 3],
         [3, 1, 6, 2],
         [9, 8, 8, 5],
         [7, 2, 5, 6],
         [5, 7, 5, 9]],

        [[9, 4, 2, 9],
         [1, 4, 4, 3],
         [5, 9, 3, 3],
         [2, 6, 2, 3],
         [8, 7, 8, 5]]])


In [3]:
# 简单索引
print(tensor1[2, 1, 3])
print(tensor1[2, 3])

tensor(3)
tensor([2, 6, 2, 3])


In [4]:
# 范围索引
print(tensor1[:, 3])
print(tensor1[1:])
print(tensor1[:, 2:4, 3])

tensor([[5, 6, 3, 3],
        [7, 2, 5, 6],
        [2, 6, 2, 3]])
tensor([[[1, 4, 8, 3],
         [3, 1, 6, 2],
         [9, 8, 8, 5],
         [7, 2, 5, 6],
         [5, 7, 5, 9]],

        [[9, 4, 2, 9],
         [1, 4, 4, 3],
         [5, 9, 3, 3],
         [2, 6, 2, 3],
         [8, 7, 8, 5]]])
tensor([[2, 3],
        [5, 6],
        [3, 3]])


In [5]:
# 列表索引
print(tensor1[[0, 1], [1, 2], [1, 3]])  # 所选取的元素坐标
print(tensor1[[[0], [1]], [1, 2]])  # 一对多的关系

tensor([7, 5])
tensor([[[8, 7, 4, 1],
         [8, 3, 1, 2]],

        [[3, 1, 6, 2],
         [9, 8, 8, 5]]])


In [6]:
# 布尔索引
mask = tensor1[:, :, 0] > 5  # 判断每行首元素是否大于5
print(mask)
print(tensor1[mask])

tensor([[False,  True,  True, False, False],
        [False, False,  True,  True, False],
        [ True, False, False, False,  True]])
tensor([[8, 7, 4, 1],
        [8, 3, 1, 2],
        [9, 8, 8, 5],
        [7, 2, 5, 6],
        [9, 4, 2, 9],
        [8, 7, 8, 5]])


In [7]:
mask = tensor1[:, 1, :] > 5  # 判断每列第二个元素是否大于5
print(mask)
tensor2 = tensor1.permute(0, 2, 1)  # permute：一般化的转置
print(tensor2[mask])

tensor([[ True,  True, False, False],
        [False, False,  True, False],
        [False, False, False, False]])
tensor([[1, 8, 8, 5, 4],
        [9, 7, 3, 6, 8],
        [8, 6, 8, 5, 5]])


In [8]:
# 选取符合条件的矩阵
mask = tensor1[:, 0, 1] > 7
print(mask)
print(tensor1[mask])

tensor([ True, False, False])
tensor([[[1, 9, 9, 7],
         [8, 7, 4, 1],
         [8, 3, 1, 2],
         [5, 6, 3, 3],
         [4, 8, 8, 5]]])
