In [1]:
import torch

# 张量形状操作

In [3]:
tensor1 = torch.randint(1, 20, (2, 3, 6))
print(tensor1)

tensor([[[15, 14, 13,  8,  3, 11],
         [12,  3, 13, 16,  5,  2],
         [ 4,  1,  9,  6, 13, 12]],

        [[14, 11,  3,  8,  3, 13],
         [19, 10,  8,  9, 15,  6],
         [19, 15, 11, 17,  1, 13]]])


In [4]:
# 交换两个维度
print(tensor1.transpose(1, 2))

tensor([[[15, 12,  4],
         [14,  3,  1],
         [13, 13,  9],
         [ 8, 16,  6],
         [ 3,  5, 13],
         [11,  2, 12]],

        [[14, 19, 19],
         [11, 10, 15],
         [ 3,  8, 11],
         [ 8,  9, 17],
         [ 3, 15,  1],
         [13,  6, 13]]])


In [5]:
# 重新排列多个维度
print(tensor1.permute(2, 1, 0))

tensor([[[15, 14],
         [12, 19],
         [ 4, 19]],

        [[14, 11],
         [ 3, 10],
         [ 1, 15]],

        [[13,  3],
         [13,  8],
         [ 9, 11]],

        [[ 8,  8],
         [16,  9],
         [ 6, 17]],

        [[ 3,  3],
         [ 5, 15],
         [13,  1]],

        [[11, 13],
         [ 2,  6],
         [12, 13]]])


In [10]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

tensor([[[7, 7, 4, 1],
         [9, 3, 2, 6],
         [6, 7, 4, 4],
         [1, 9, 4, 5],
         [7, 1, 4, 2]],

        [[8, 3, 2, 2],
         [7, 8, 8, 2],
         [4, 1, 6, 6],
         [9, 7, 9, 5],
         [1, 8, 9, 9]],

        [[9, 8, 2, 5],
         [3, 4, 9, 6],
         [1, 5, 7, 6],
         [5, 2, 8, 5],
         [6, 1, 2, 3]]])


In [12]:
# 调整形状
print(tensor1.reshape((6, 10)))  # 各维度相乘要与原张量各维度相乘结果相同

tensor([[7, 7, 4, 1, 9, 3, 2, 6, 6, 7],
        [4, 4, 1, 9, 4, 5, 7, 1, 4, 2],
        [8, 3, 2, 2, 7, 8, 8, 2, 4, 1],
        [6, 6, 9, 7, 9, 5, 1, 8, 9, 9],
        [9, 8, 2, 5, 3, 4, 9, 6, 1, 5],
        [7, 6, 5, 2, 8, 5, 6, 1, 2, 3]])


In [16]:
# view() 调整张量的形状，需要内存连续，共享内存
print(tensor1.is_contiguous())  # 判断张量是否内存连续，若是将张量进行反转，则会造成不连续
# tensor1.contiguous()  # 将张量转化为内存连续
print(tensor1.view(-1, 10))
print(tensor1.shape)

True
tensor([[7, 7, 4, 1, 9, 3, 2, 6, 6, 7],
        [4, 4, 1, 9, 4, 5, 7, 1, 4, 2],
        [8, 3, 2, 2, 7, 8, 8, 2, 4, 1],
        [6, 6, 9, 7, 9, 5, 1, 8, 9, 9],
        [9, 8, 2, 5, 3, 4, 9, 6, 1, 5],
        [7, 6, 5, 2, 8, 5, 6, 1, 2, 3]])
torch.Size([3, 5, 4])


In [23]:
# 增加或删除维度，最后一个维度为-1维度，同样 unsqueeze_()方法可以原地操作
tensor1 = torch.tensor([1, 2, 3, 4, 5])
# print(tensor1.unsqueeze(0)) # 在0维度上添加一个维度
print(tensor1.unsqueeze_(1)) # 在维度1上添加一个维度

print(tensor1.squeeze(1))   # 要求对维度为1的维度进行压缩

tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([1, 2, 3, 4, 5])
