In [1]:
import torch

# 张量形状操作

In [2]:
tensor1 = torch.randint(1, 20, (2, 3, 6))
print(tensor1)

tensor([[[14, 17,  9,  9, 17, 18],
         [10,  2,  3, 18,  6,  2],
         [11,  5,  1, 14,  3,  2]],

        [[ 6,  4, 12,  7, 11, 18],
         [ 1, 17, 19, 10,  7,  5],
         [ 4,  4, 19,  8, 11,  8]]])


In [3]:
# 交换两个维度
print(tensor1.transpose(1, 2))

tensor([[[14, 10, 11],
         [17,  2,  5],
         [ 9,  3,  1],
         [ 9, 18, 14],
         [17,  6,  3],
         [18,  2,  2]],

        [[ 6,  1,  4],
         [ 4, 17,  4],
         [12, 19, 19],
         [ 7, 10,  8],
         [11,  7, 11],
         [18,  5,  8]]])


In [4]:
# 重新排列多个维度
print(tensor1.permute(2, 1, 0))

tensor([[[14,  6],
         [10,  1],
         [11,  4]],

        [[17,  4],
         [ 2, 17],
         [ 5,  4]],

        [[ 9, 12],
         [ 3, 19],
         [ 1, 19]],

        [[ 9,  7],
         [18, 10],
         [14,  8]],

        [[17, 11],
         [ 6,  7],
         [ 3, 11]],

        [[18, 18],
         [ 2,  5],
         [ 2,  8]]])


In [5]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

tensor([[[7, 2, 4, 4],
         [6, 1, 3, 3],
         [1, 3, 7, 6],
         [9, 3, 5, 9],
         [1, 4, 6, 9]],

        [[5, 2, 8, 6],
         [4, 1, 4, 1],
         [1, 4, 5, 2],
         [8, 6, 6, 9],
         [1, 1, 1, 1]],

        [[2, 1, 8, 3],
         [2, 5, 5, 9],
         [4, 6, 8, 2],
         [1, 4, 5, 7],
         [7, 6, 2, 9]]])


In [6]:
# 调整形状
print(tensor1.reshape((6, 10)))  # 各维度相乘要与原张量各维度相乘结果相同

tensor([[7, 2, 4, 4, 6, 1, 3, 3, 1, 3],
        [7, 6, 9, 3, 5, 9, 1, 4, 6, 9],
        [5, 2, 8, 6, 4, 1, 4, 1, 1, 4],
        [5, 2, 8, 6, 6, 9, 1, 1, 1, 1],
        [2, 1, 8, 3, 2, 5, 5, 9, 4, 6],
        [8, 2, 1, 4, 5, 7, 7, 6, 2, 9]])


In [7]:
# view() 调整张量的形状，需要内存连续，共享内存
print(tensor1.is_contiguous())  # 判断张量是否内存连续，若是将张量进行反转，则会造成不连续
# tensor1.contiguous()  # 将张量转化为内存连续
print(tensor1.view(-1, 10))
print(tensor1.shape)

True
tensor([[7, 2, 4, 4, 6, 1, 3, 3, 1, 3],
        [7, 6, 9, 3, 5, 9, 1, 4, 6, 9],
        [5, 2, 8, 6, 4, 1, 4, 1, 1, 4],
        [5, 2, 8, 6, 6, 9, 1, 1, 1, 1],
        [2, 1, 8, 3, 2, 5, 5, 9, 4, 6],
        [8, 2, 1, 4, 5, 7, 7, 6, 2, 9]])
torch.Size([3, 5, 4])


In [8]:
# 增加或删除维度，最后一个维度为-1维度，同样 unsqueeze_()方法可以原地操作
tensor1 = torch.tensor([1, 2, 3, 4, 5])
# print(tensor1.unsqueeze(0)) # 在0维度上添加一个维度
print(tensor1.unsqueeze_(1)) # 在维度1上添加一个维度

print(tensor1.squeeze(1))   # 要求对维度为1的维度进行压缩

tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([1, 2, 3, 4, 5])


In [9]:
tensor1 = torch.randint(1, 10, (2, 3, 5))
tensor2 = torch.randint(1, 10, (2, 3, 5))
print(tensor1)
print(tensor2)
# 张量的拼接
print(torch.cat((tensor1, tensor2), dim=1))

tensor([[[9, 2, 4, 6, 5],
         [6, 8, 6, 6, 9],
         [3, 6, 3, 6, 6]],

        [[4, 2, 4, 4, 7],
         [3, 5, 9, 7, 3],
         [4, 9, 6, 1, 4]]])
tensor([[[3, 9, 9, 6, 7],
         [3, 7, 2, 5, 3],
         [9, 1, 3, 5, 5]],

        [[6, 1, 3, 7, 3],
         [7, 5, 8, 9, 2],
         [4, 1, 9, 8, 6]]])
tensor([[[9, 2, 4, 6, 5],
         [6, 8, 6, 6, 9],
         [3, 6, 3, 6, 6],
         [3, 9, 9, 6, 7],
         [3, 7, 2, 5, 3],
         [9, 1, 3, 5, 5]],

        [[4, 2, 4, 4, 7],
         [3, 5, 9, 7, 3],
         [4, 9, 6, 1, 4],
         [6, 1, 3, 7, 3],
         [7, 5, 8, 9, 2],
         [4, 1, 9, 8, 6]]])


In [10]:
tensor1 = torch.randint(1, 10, (2, 3, 5))
tensor2 = torch.randint(1, 10, (2, 3, 5))
print(tensor1)
print(tensor2)

tensor3 = torch.stack((tensor1, tensor2), dim=0) # 2 4 3 5
print(tensor3)
tensor3 = torch.stack((tensor1, tensor2), dim=1) # 4 2 3 5
print(tensor3)

tensor([[[7, 5, 2, 8, 2],
         [5, 5, 7, 5, 5],
         [3, 3, 6, 9, 6]],

        [[5, 1, 7, 5, 7],
         [8, 5, 7, 3, 2],
         [5, 3, 4, 9, 1]]])
tensor([[[1, 4, 3, 6, 9],
         [5, 1, 2, 6, 5],
         [9, 4, 9, 3, 9]],

        [[5, 8, 6, 3, 2],
         [9, 4, 5, 6, 7],
         [8, 2, 1, 8, 7]]])
tensor([[[[7, 5, 2, 8, 2],
          [5, 5, 7, 5, 5],
          [3, 3, 6, 9, 6]],

         [[5, 1, 7, 5, 7],
          [8, 5, 7, 3, 2],
          [5, 3, 4, 9, 1]]],


        [[[1, 4, 3, 6, 9],
          [5, 1, 2, 6, 5],
          [9, 4, 9, 3, 9]],

         [[5, 8, 6, 3, 2],
          [9, 4, 5, 6, 7],
          [8, 2, 1, 8, 7]]]])
tensor([[[[7, 5, 2, 8, 2],
          [5, 5, 7, 5, 5],
          [3, 3, 6, 9, 6]],

         [[1, 4, 3, 6, 9],
          [5, 1, 2, 6, 5],
          [9, 4, 9, 3, 9]]],


        [[[5, 1, 7, 5, 7],
          [8, 5, 7, 3, 2],
          [5, 3, 4, 9, 1]],

         [[5, 8, 6, 3, 2],
          [9, 4, 5, 6, 7],
          [8, 2, 1, 8, 7]]]])
