# 张量创建

In [1]:
import torch
import numpy as np

## 1. 基本张量创建

## 1.1. `torch.tensor(data)`创建指定内容的张量

In [2]:
# 创建标量张量
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [3]:
# 使用列表创建张量
tensor2 = torch.tensor([1, 2, 3])
print(tensor2)

tensor([1, 2, 3])


In [4]:
# 使用numpy数组创建张量
tensor3 = torch.tensor(np.random.randint(low=1, high=10, size=(3, 2)))
print(tensor3)

tensor([[7, 9],
        [8, 3],
        [1, 7]], dtype=torch.int32)


## 1.2. `torch.Tensor(size)`创建指定形状的张量

In [5]:
tensor1 = torch.Tensor(3, 2, 4)  # 创建指定形状的张量，默认类型为float32
print(tensor1, tensor1.dtype)

tensor([[[4.1338e-28, 1.0608e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]]) torch.float32


In [6]:
tensor2 = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8]])  # 也可以用来创建指定内容的张量
print(tensor2)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


## 1.3 创建指定类型的张量

> 可以通过`torch.IntTensor()`、`torch.FloatTensor()`等创建，也可以通过`torch.tensor()`中通过`dtype`参数指定类型

In [8]:
tensor1 = torch.IntTensor(3, 2)
print(tensor1, tensor1.dtype)
tensor1 = torch.tensor([2, 3, 4], dtype=torch.int32)
print(tensor1)
tensor1 = torch.IntTensor([3, 2.6])  # 按照内容创建时，若类型不匹配会进行类型撞昏
print(tensor1, tensor1.dtype)
tensor1 = torch.tensor([2.4, 3.1, 4.8], dtype=torch.int32)
print(tensor1)

tensor([[302122592,       757],
        [        0,         0],
        [        0,         0]], dtype=torch.int32) torch.int32
tensor([2, 3, 4], dtype=torch.int32)
tensor([3, 2], dtype=torch.int32) torch.int32
tensor([2, 3, 4], dtype=torch.int32)


# 2. 指定区间创建张量

## 2.1. `torch.arange(start, end, step)`再区间内按步长创建张量

In [9]:
tensor1 = torch.arange(start=10, end=20, step=2)
print(tensor1)

tensor([10, 12, 14, 16, 18])


In [10]:
tensor2 = torch.arange(10)  # torch.arange(end)创建区间为创建区间为[0, end)，步长为1的张量
print(tensor2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## 2.2. `torch.linspace(start, end, steps)`在区间内按元素数量创建张量

In [12]:
tensor1 = torch.linspace(start=0, end=10, steps=5)
print(tensor1)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


## 2.3. `torch.logspace(start, end, steps, base)`在指数区间按指底数创建张量

In [14]:
tensor1 = torch.logspace(start=1, end=10, steps=10,
                         base=2)  # torch.logspace(start, end, steps, base)在区间[start, end]之间生成steps个数，并以base为底，区间的数为指数创建张量
print(tensor1)

tensor([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512., 1024.])


# 3. 按数值填充张量

与`Numpy`类似：
* `torch.zeros(size)`创建指定形状的全0张量
* `torch.ones(size)`创建指定形状的全1张量
* `torch.full(size, value)`创建指定形状的按指定值填充的张量
* `torch.empty(size)`创建指定形状的未初始化的张量
* `torch.zeros_like(input)`创建与给定张量形状完全相同的全0张量
* `torch.ones_like(input)`创建与给定张量形状完全相同的全1张量
* `torch.full_like(input, value)`创建与给定张量形状完全相同的按指定值填充的张量
* `torch.empty_like(input, value)`创建与给定张量形状完全相同的未初始化的张量
* `torch.eye(n, [m])`创建单位矩阵

In [16]:
tensor1 = torch.eye(3)  # torch.eye(n) 创建 n * n 的单位矩阵
print(tensor1)

tensor2 = torch.eye(3, 4)  # torch.eye(n, m) 创建 n * m 的单位矩阵
print(tensor2)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


# 4. 随机张量创建

与`Numpy`相似：
* `torch.rand(size)`创建在[0, 1)上均匀分布，指定形状的张量
* `torch.randint(log, high, size)`创建在[low, high)上均匀分布，指定形状的张量
* `torch.randn(size)`创建标准正态分布，指定形状的张量
* `torch.normal(mean, std, size)`创建自定义正态分布的，指定形状的张量
* `torch.rand_like(input)`创建在[0, 1)上均匀分布的，与给定张量形状相同的张量
* `torch.randint_like(input, low, high)`创建在[low, high)上均匀分布的，与给定张量形状相同的张量
* `torch.randn_like(input)`创建标准正太分布的，与给定张量形状相同的张量
* `torch.randperm(n)`生成从0到n-1的随机排列

In [20]:
tensor1 = torch.randperm(10)
print(tensor1)

tensor([7, 5, 9, 3, 1, 8, 6, 4, 0, 2])


* `torch.random.initial_seed()`查看随机数种子
* `torch.manual_seed(seed)`设置随机数种子

In [21]:
torch.manual_seed(42)
print(torch.random.initial_seed())

42
