# 张量索引操作

In [1]:
import torch

tensor1 = torch.randint(low=1, high=9, size=(3, 5, 4))
tensor1

tensor([[[3, 1, 6, 7],
         [3, 5, 4, 2],
         [5, 1, 4, 2],
         [7, 7, 3, 4],
         [4, 3, 4, 1]],

        [[1, 5, 8, 8],
         [1, 6, 6, 3],
         [4, 6, 3, 7],
         [6, 4, 2, 5],
         [3, 8, 8, 3]],

        [[3, 5, 1, 6],
         [6, 6, 2, 3],
         [2, 2, 2, 1],
         [1, 1, 5, 5],
         [5, 8, 4, 6]]])

# 1. 简单索引

In [12]:
tensor1[0]

tensor([[3, 1, 6, 7],
        [3, 5, 4, 2],
        [5, 1, 4, 2],
        [7, 7, 3, 4],
        [4, 3, 4, 1]])

In [3]:
tensor1[:, 1]  # 第0维所有，第1维下标为1的元素

tensor([[3, 5, 4, 2],
        [1, 6, 6, 3],
        [6, 6, 2, 3]])

In [4]:
tensor1[:, 1, 3]  # 取第0维所有，第1维下标为1，第2维下标为3的所有元素

tensor([2, 3, 3])

# 2. 范围索引

In [5]:
# 取第0维下标1到最后
tensor1[1:]

tensor([[[1, 5, 8, 8],
         [1, 6, 6, 3],
         [4, 6, 3, 7],
         [6, 4, 2, 5],
         [3, 8, 8, 3]],

        [[3, 5, 1, 6],
         [6, 6, 2, 3],
         [2, 2, 2, 1],
         [1, 1, 5, 5],
         [5, 8, 4, 6]]])

In [6]:
# 取第0维最后，第1维下标1到3（包含），第2维下标0到2（包含）
tensor1[-1, 1:4, 0:3]

tensor([[6, 6, 2],
        [2, 2, 2],
        [1, 1, 5]])

# 3. 列表索引

In [7]:
# 取 第0维下标0、1和 第1维下标1、2
tensor1[[0, 1], [1, 2]]

tensor([[3, 5, 4, 2],
        [4, 6, 3, 7]])

In [8]:
# 取 第0维下标0 第1维下标1、2 和 第0维下标1第1维下标1、2
tensor1[[[0], [1]], [1, 2]]

tensor([[[3, 5, 4, 2],
         [5, 1, 4, 2]],

        [[1, 6, 6, 3],
         [4, 6, 3, 7]]])

# 4. 布尔索引

In [18]:
# 取 第2维第0大于5的，返回(dim0,dim1)形状的索引
tensor1[tensor1[:,:,0] > 5]

tensor([[7, 7, 3, 4],
        [6, 4, 2, 5],
        [6, 6, 2, 3]])

In [10]:
# 取 第1维第1大于5的，返回(dim0,dim2)形状的索引
mask = tensor1[:,1,:] > 5
print(mask)

tensor2 = tensor1.permute(0, 2, 1)  # 转换维度为(dim0, dim, dim1)
print(tensor2[mask])
tensor2 = tensor2[mask].permute(1, 0)   # 转化维度为(dim1, ?)
print(tensor2)

tensor([[False, False, False, False],
        [False,  True,  True, False],
        [ True,  True, False, False]])
tensor([[5, 6, 6, 4, 8],
        [8, 6, 3, 2, 8],
        [3, 6, 2, 1, 5],
        [5, 6, 2, 1, 8]])
tensor([[5, 8, 3, 5],
        [6, 6, 6, 6],
        [6, 3, 2, 2],
        [4, 2, 1, 1],
        [8, 8, 5, 8]])


In [22]:
# 取 第1维第2维大于5的，返回(dim0,dim2)形状的索引
tensor1[tensor1[:,1, 2] > 5]

tensor([[[1, 5, 8, 8],
         [1, 6, 6, 3],
         [4, 6, 3, 7],
         [6, 4, 2, 5],
         [3, 8, 8, 3]]])