# 张量形状操作

In [2]:
import torch

tensor1 = torch.randint(1, 9, (2, 3, 6))
tensor1

tensor([[[4, 8, 1, 1, 4, 8],
         [6, 5, 2, 6, 5, 5],
         [2, 2, 2, 3, 8, 1]],

        [[3, 1, 4, 1, 3, 7],
         [4, 1, 2, 3, 7, 2],
         [3, 7, 3, 1, 6, 8]]])

## 1. 交换维度

* `transpose()`交换两个维度

In [3]:
tensor1.transpose(1, 2)  # 交换第1维和第2维

tensor([[[4, 6, 2],
         [8, 5, 2],
         [1, 2, 2],
         [1, 6, 3],
         [4, 5, 8],
         [8, 5, 1]],

        [[3, 4, 3],
         [1, 1, 7],
         [4, 2, 3],
         [1, 3, 1],
         [3, 7, 6],
         [7, 2, 8]]])

* `permute()`重排列多个维度

In [4]:
tensor1.permute(2, 0, 1)  # (2, 3, 6) -> (6, 2, 3)

tensor([[[4, 6, 2],
         [3, 4, 3]],

        [[8, 5, 2],
         [1, 1, 7]],

        [[1, 2, 2],
         [4, 2, 3]],

        [[1, 6, 3],
         [1, 3, 1]],

        [[4, 5, 8],
         [3, 7, 6]],

        [[8, 5, 1],
         [7, 2, 8]]])

# 2. 调整形状

* `reshape()`调整张量维度

In [5]:
tensor1.reshape(6, 6), tensor1.reshape((12, 3))

(tensor([[4, 8, 1, 1, 4, 8],
         [6, 5, 2, 6, 5, 5],
         [2, 2, 2, 3, 8, 1],
         [3, 1, 4, 1, 3, 7],
         [4, 1, 2, 3, 7, 2],
         [3, 7, 3, 1, 6, 8]]),
 tensor([[4, 8, 1],
         [1, 4, 8],
         [6, 5, 2],
         [6, 5, 5],
         [2, 2, 2],
         [3, 8, 1],
         [3, 1, 4],
         [1, 3, 7],
         [4, 1, 2],
         [3, 7, 2],
         [3, 7, 3],
         [1, 6, 8]]))

* `view()`调账张量形状，需要内存连续，内存共享
* `is_contiguous()`判断是否内存连续
* `coutiguous()`转化维连续内存

In [6]:
tensor1 = tensor1.reshape(6, 6)
print(tensor1, tensor1.is_contiguous())
print(tensor1.view(-1, 12))

tensor2 = tensor1.T
print(tensor2, tensor2.is_contiguous())
tensor2.contiguous()
print(tensor2.contiguous().view(-1, 12))

tensor([[4, 8, 1, 1, 4, 8],
        [6, 5, 2, 6, 5, 5],
        [2, 2, 2, 3, 8, 1],
        [3, 1, 4, 1, 3, 7],
        [4, 1, 2, 3, 7, 2],
        [3, 7, 3, 1, 6, 8]]) True
tensor([[4, 8, 1, 1, 4, 8, 6, 5, 2, 6, 5, 5],
        [2, 2, 2, 3, 8, 1, 3, 1, 4, 1, 3, 7],
        [4, 1, 2, 3, 7, 2, 3, 7, 3, 1, 6, 8]])
tensor([[4, 6, 2, 3, 4, 3],
        [8, 5, 2, 1, 1, 7],
        [1, 2, 2, 4, 2, 3],
        [1, 6, 3, 1, 3, 1],
        [4, 5, 8, 3, 7, 6],
        [8, 5, 1, 7, 2, 8]]) False
tensor([[4, 6, 2, 3, 4, 3, 8, 5, 2, 1, 1, 7],
        [1, 2, 2, 4, 2, 3, 1, 6, 3, 1, 3, 1],
        [4, 5, 8, 3, 7, 6, 8, 5, 1, 7, 2, 8]])


## 3. 增加或删除维度

* `unsqueeze()`在指定维度上增加1个维度

In [7]:
tensor1 = torch.tensor([1, 2, 3, 4, 5])
print(tensor1)

print(tensor1.unsqueeze(dim=0)) # 在第0维上增加一个维度
print(tensor1.unsqueeze(dim=1)) # 在第1维上增加一个维度

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])


* `squeeze()`删除大小为1的维度

In [10]:
tensor1 = torch.tensor([1, 2, 3, 4, 5])
print(tensor1.unsqueeze_(dim=1))
print(tensor1.squeeze())

tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([1, 2, 3, 4, 5])
