# 张量运算函数

In [9]:
import torch

tensor1 = torch.randint(low=1, high=9, size=(3, 2, 4))
tensor1

tensor([[[1, 2, 7, 2],
         [8, 1, 1, 5]],

        [[6, 1, 5, 4],
         [7, 6, 5, 8]],

        [[8, 5, 6, 7],
         [7, 1, 2, 7]]])

* `sum()`求和

In [10]:
tensor1.sum(), tensor1.sum(dim=(0, 1))  # 通过dim参数指定求和的维度

(tensor(112), tensor([37, 16, 26, 33]))

* `mean()`求均值

In [11]:
tensor1 = tensor1.float()
tensor1.mean(), tensor1.mean(dim=(0, 1))

(tensor(4.6667), tensor([6.1667, 2.6667, 4.3333, 5.5000]))

* `max()/min()`求最大值/最小值及其索引

In [12]:
tensor1.max(), tensor1.max(dim=1), tensor1.min(), tensor1.min(dim=1)

(tensor(8.),
 torch.return_types.max(
 values=tensor([[8., 2., 7., 5.],
         [7., 6., 5., 8.],
         [8., 5., 6., 7.]]),
 indices=tensor([[1, 0, 0, 1],
         [1, 1, 0, 1],
         [0, 0, 0, 0]])),
 tensor(1.),
 torch.return_types.min(
 values=tensor([[1., 1., 1., 2.],
         [6., 1., 5., 4.],
         [7., 1., 2., 7.]]),
 indices=tensor([[0, 1, 1, 0],
         [0, 0, 0, 0],
         [1, 1, 1, 0]])))

* `argmax()/argmin()`求最大值/最小值的索引

In [13]:
tensor1.argmax(), tensor1.argmax(dim=1), tensor1.argmin(), tensor1.argmin(dim=1)

(tensor(4),
 tensor([[1, 0, 0, 1],
         [1, 1, 0, 1],
         [0, 0, 0, 0]]),
 tensor(0),
 tensor([[0, 1, 1, 0],
         [0, 0, 0, 0],
         [1, 1, 1, 0]]))

* `std()`求标准差

In [14]:
tensor1.std()

tensor(2.5988)

* `unique()`去重

In [15]:
tensor1.unique()

tensor([1., 2., 4., 5., 6., 7., 8.])

`sort()`排序

In [16]:
tensor1.sort()

torch.return_types.sort(
values=tensor([[[1., 2., 2., 7.],
         [1., 1., 5., 8.]],

        [[1., 4., 5., 6.],
         [5., 6., 7., 8.]],

        [[5., 6., 7., 8.],
         [1., 2., 7., 7.]]]),
indices=tensor([[[0, 1, 3, 2],
         [1, 2, 3, 0]],

        [[1, 3, 2, 0],
         [2, 1, 0, 3]],

        [[1, 2, 3, 0],
         [1, 2, 0, 3]]]))