# 张量转换

In [1]:
import torch
import numpy as np

## 1. 张量元素类型转换

## 1.1. `Tensor.type(dtype)`修改张量的类型

In [2]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1, tensor1.dtype)

# 使用type方法修改张量的类型
tensor1 = tensor1.type(torch.float32)
print(tensor1, tensor1.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32


## 1.2. `Tensor.double()`等修改张量的类型

In [3]:
tensor1 = torch.tensor([1, 2, 3])

tensor1 = tensor1.double()
print(tensor1, tensor1.dtype)
tensor1 = tensor1.bool()
print(tensor1, tensor1.dtype)
tensor1 = tensor1.long()
print(tensor1, tensor1.dtype)

tensor([1., 2., 3.], dtype=torch.float64) torch.float64
tensor([True, True, True]) torch.bool
tensor([1, 1, 1]) torch.int64


# 2. Tensor与ndarray转换

## 2.1. `Tensor.numpy()`将Tensor转化为ndarray，共享内存，使用`copy()`避免内存共享

In [4]:
tensor1 = torch.rand(3, 2)
print(tensor1)

arr1 = tensor1.numpy()
print(arr1)
print(type(tensor1), type(arr1))
print('-' * 50)

tensor1[:, 0] = 4
print(tensor1)
print(arr1)
print('-' * 50)

# 使用copy()方法避免共享内存
arr2 = tensor1.numpy().copy()
tensor1[:, 0] = -1
print(tensor1)
print(arr2)

tensor([[0.2419, 0.3840],
        [0.8555, 0.4871],
        [0.6381, 0.4638]])
[[0.2419138  0.38398665]
 [0.85553074 0.4871143 ]
 [0.63812417 0.46384436]]
<class 'torch.Tensor'> <class 'numpy.ndarray'>
--------------------------------------------------
tensor([[4.0000, 0.3840],
        [4.0000, 0.4871],
        [4.0000, 0.4638]])
[[4.         0.38398665]
 [4.         0.4871143 ]
 [4.         0.46384436]]
--------------------------------------------------
tensor([[-1.0000,  0.3840],
        [-1.0000,  0.4871],
        [-1.0000,  0.4638]])
[[4.         0.38398665]
 [4.         0.4871143 ]
 [4.         0.46384436]]


## 2.2. `torch.from_numpy(ndarray)`将ndarray转化为Tensor，使用`copy()`避免共享内存

In [5]:
arr = np.random.randint(low=1, high=10, size=(3, 4))

tensor1 = torch.from_numpy(arr)
print(arr)
print(tensor1)
arr[:, 2] = -1
print('-' * 50)

print(arr)
print(tensor1)
print('-' * 50)

tensor2 = torch.from_numpy(arr.copy())
arr[1, :] = 100
print(arr)
print(tensor2)

[[3 2 8 9]
 [5 3 2 8]
 [6 2 7 3]]
tensor([[3, 2, 8, 9],
        [5, 3, 2, 8],
        [6, 2, 7, 3]], dtype=torch.int32)
--------------------------------------------------
[[ 3  2 -1  9]
 [ 5  3 -1  8]
 [ 6  2 -1  3]]
tensor([[ 3,  2, -1,  9],
        [ 5,  3, -1,  8],
        [ 6,  2, -1,  3]], dtype=torch.int32)
--------------------------------------------------
[[  3   2  -1   9]
 [100 100 100 100]
 [  6   2  -1   3]]
tensor([[ 3,  2, -1,  9],
        [ 5,  3, -1,  8],
        [ 6,  2, -1,  3]], dtype=torch.int32)


## 2.3. `torch.tensor(ndarray)`将ndarray转化为Tensor，不共享内存

In [8]:
arr = np.random.normal(loc=10, scale=2, size=(3, 4))
tensor1 = torch.tensor(arr)
print(arr)
print(tensor1)
print('-' * 50)

arr[0:4:2, 1:6:2] = 3
print(arr)
print(tensor1)

[[10.87464369 10.94766436 12.11497243 12.33181266]
 [10.76621609 10.02800272 11.4297506   6.97350883]
 [ 7.85115785  8.37744329 10.8254821   8.86793454]]
tensor([[10.8746, 10.9477, 12.1150, 12.3318],
        [10.7662, 10.0280, 11.4298,  6.9735],
        [ 7.8512,  8.3774, 10.8255,  8.8679]], dtype=torch.float64)
--------------------------------------------------
[[10.87464369  3.         12.11497243  3.        ]
 [10.76621609 10.02800272 11.4297506   6.97350883]
 [ 7.85115785  3.         10.8254821   3.        ]]
tensor([[10.8746, 10.9477, 12.1150, 12.3318],
        [10.7662, 10.0280, 11.4298,  6.9735],
        [ 7.8512,  8.3774, 10.8255,  8.8679]], dtype=torch.float64)


# 3. Tensor与标量转化

若张量中只有一个元素，`Tensor.item()`可以提取张量中的元素为标量

In [10]:
tensor1 = torch.tensor(5)
print(tensor1)
print(tensor1.item(), type(tensor1.item()))

tensor(5)
5 <class 'int'>
