# 张量拼接操作

In [1]:
import torch

tensor1 = torch.randint(1, 9, (2, 2, 5))
tensor2 = torch.randint(1, 9, (2, 2, 5))
tensor1, tensor2

(tensor([[[5, 4, 1, 6, 6],
          [1, 6, 5, 4, 2]],
 
         [[5, 3, 7, 4, 4],
          [1, 2, 3, 4, 2]]]),
 tensor([[[4, 1, 7, 3, 6],
          [5, 8, 7, 3, 6]],
 
         [[5, 1, 4, 2, 4],
          [8, 4, 3, 5, 2]]]))

* `torch.cat()`张量拼接，按已有维度拼接。除拼接维度外，其他维度大小必须相同

In [2]:
torch.cat([tensor1, tensor2], dim=1)

tensor([[[5, 4, 1, 6, 6],
         [1, 6, 5, 4, 2],
         [4, 1, 7, 3, 6],
         [5, 8, 7, 3, 6]],

        [[5, 3, 7, 4, 4],
         [1, 2, 3, 4, 2],
         [5, 1, 4, 2, 4],
         [8, 4, 3, 5, 2]]])

* `torch.stack()`张量堆叠，按新维度堆叠，所有张量形状必须一致

In [4]:
tensor3 = torch.stack([tensor1, tensor2], dim=2)
tensor3, tensor3.shape

(tensor([[[[5, 4, 1, 6, 6],
           [4, 1, 7, 3, 6]],
 
          [[1, 6, 5, 4, 2],
           [5, 8, 7, 3, 6]]],
 
 
         [[[5, 3, 7, 4, 4],
           [5, 1, 4, 2, 4]],
 
          [[1, 2, 3, 4, 2],
           [8, 4, 3, 5, 2]]]]),
 torch.Size([2, 2, 2, 5]))