# Numpy数组(ndarray)性质和创建

* 多维性：支持0维（标量）、1维（向量）、2维（矩阵）及更高维数组
* 同质性：所有元素类型必须一致（通过`dtype`指定）
* 高效性：基于连续内存块存储，支持向量化运算

In [2]:
import numpy as np

In [10]:
arr = np.array(5)  # 创建0维ndarray数组
print(arr, arr.ndim)

5 0


In [11]:
arr = np.array([1, 2, 3, 4])  # 创建1维ndarray数组，和Python列表创建方式一致
print(arr, arr.ndim)

[1 2 3 4] 1


In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # 创建2维ndarray数组，和Python列表创建方式一致
print(arr, arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 2


In [14]:
arr = np.array([1, 2.3, 'hello'])  # 同质性：不同的数据类型会被自动转化为相同的数据类型
print(arr)

['1' '2.3' 'hello']


## 1. 核心属性

In [23]:
arr = np.array([[10, 20, 30, 40, 50, 60.], [1, 2, 3, 4, 5, 6]])
print(arr)

[[10. 20. 30. 40. 50. 60.]
 [ 1.  2.  3.  4.  5.  6.]]


* `shape`：数组的形状

In [22]:
arr.shape

(2, 6)

* `ndim`：数组维度

In [24]:
arr.ndim

2

* `size`：数组中元素个数

In [25]:
arr.size

12

* `dtype`：数组中元素类型

In [26]:
arr.dtype

dtype('float64')

* `T`：转置

In [27]:
arr.T

array([[10.,  1.],
       [20.,  2.],
       [30.,  3.],
       [40.,  4.],
       [50.,  5.],
       [60.,  6.]])

* `itemsize`：单个元素占用的内存字节数

In [28]:
arr.itemsize

8

* `nbytes`：数组总内存占用量：`size * itemsize`

In [29]:
arr.nbytes

96

* `flags`：内存存储方式：是否连续存储（高级优化）

In [30]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [32]:
arr = arr.T
arr.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

# 2. 创建方式

## 2.1 基础创建方式

In [39]:
l = [1, 2, 3]
arr = np.array(l, dtype=np.float32)  # 类似于Python中列表创建方式，也可以直接通过Python列表创建
print(arr)

[1. 2. 3.]


## 2.2 copy方式

In [40]:
arr_copy = np.copy(arr)  # 深拷贝，步共享内存
print(arr_copy, id(arr_copy), id(arr))

[1. 2. 3.] 1831635432816 1831635433968


## 2.3 预定义形状方式

In [46]:
arr1 = np.zeros(shape=(3, 4), dtype=np.int32)  # 全0数组
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [47]:
arr2 = np.ones(shape=(2, 1, 3))  # 全1数组，默认类型为float64
print(arr2, arr2.dtype)

[[[1. 1. 1.]]

 [[1. 1. 1.]]] float64


In [54]:
arr3 = np.empty(shape=(5))  # 未初始化，执行效率更快
print(arr3, arr3.dtype)

[0.   0.25 0.5  0.75 1.  ] float64


In [55]:
arr4 = np.full(shape=(2, 3), fill_value=3)  # 自定义值填充
print(arr4, arr4.dtype)

[[3 3 3]
 [3 3 3]] int64


In [57]:
arr5 = np.zeros_like(arr4)
arr6 = np.ones_like(arr4)
arr7 = np.empty_like(arr4)
arr8 = np.full_like(arr4, 2026)
print(arr5)
print(arr6)
print(arr7)
print(arr8)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]
[[2026 2026 2026]
 [2026 2026 2026]]


## 2.4 等差数列

In [58]:
arr = np.arange(start=0, stop=10, step=2)
arr

array([0, 2, 4, 6, 8])

In [63]:
arr = np.linspace(start=1, stop=10, num=5)  # 从start开始到stop结束，等间距取num份
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [67]:
arr = np.logspace(start=1, stop=10, num=10, base=2)  # 从base^start开始，到base^stop结束，指数等间距取num份
arr

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

## 2.5 特殊矩阵生成

In [72]:
# 单位矩阵
arr = np.eye(N=3, M=4)  # N指定行数，M指定列数
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [74]:
# 对角矩阵
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [80]:
# 随机数组的生成（均匀分布）
arr = np.random.rand(2, 3)  # 生成0到1之间的随机浮点数（均匀分布）
print(arr)
arr = np.random.uniform(low=3, high=6, size=(2, 3))  # 生成指定范围之间的随机浮点数（均匀分布）
print(arr)
arr = np.random.randint(low=3, high=30, size=(2, 3))  # 生成指定范围之间的随机整数（均匀分布）
print(arr)

[[0.65791747 0.75194225 0.65012424]
 [0.69061946 0.01256033 0.60269092]]
[[4.10555782 5.19181947 3.94539375]
 [5.00355966 3.50943369 3.78758423]]
[[14 14 28]
 [16  4 13]]


In [89]:
# 随机数组的生成（正态分布）
arr = np.random.randn(2, 3)  # 生成0到1之间的随机浮点数（正态分布）
print(arr)
arr = np.random.normal(loc=80, scale=8, size=(2, 3))  # 生成指定范围之间的随机浮点数（正态分布）
print(arr)

[[ 1.99068142 -0.24142299  0.91278503]
 [-0.51037053  1.88439107 -0.4364927 ]]
[[67.94508418 84.40401097 67.15905835]
 [88.90276126 83.48190853 76.14129206]]


In [113]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(low=1, high=10, size=(2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


# 3. 数据类型

* 布尔类型 `bool`
* 整数类型 `int`、`uint`
* 浮点型 `float`
* 复数 `complex`

In [116]:
arr = np.array([1, 0, 1, 0], dtype=np.bool)  # 布尔类型
print(arr)

[ True False  True  True]


In [120]:
arr = np.array([1, -2, 3, -4], dtype=np.int32)  # 整数类型，超过数据表示范围会报错
print(arr)

[ 1 -2  3 -4]


# 4. 索引与切片

In [154]:
arr = np.array([range(1, 6), range(6, 11), range(11, 16), range(16, 21), range(21, 26)])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [173]:
print(arr[2, 2])
print(arr[1:6:2, 0:6:3])
print(arr[(arr>10) & (arr<20)])
print(arr[3:6, 1:4][(arr[3:6, 1:4]%2==0)])

13
[[ 6  9]
 [16 19]]
[11 12 13 14 15 16 17 18 19]
[18 22 24]
