# ndarray运算

In [50]:
import numpy as np

np.random.seed(42)

# ndarray数组之间的运算

In [51]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
a + b, a - b, a * b, a / b, a // b, a ** b

(array([ 3,  7, 11]),
 array([1, 1, 1]),
 array([ 2, 12, 30]),
 array([2.        , 1.33333333, 1.2       ]),
 array([2, 1, 1]),
 array([   2,   64, 7776]))

In [52]:
a = np.random.randint(low=1, high=10, size=(3, 3))
b = np.random.randint(low=1, high=10, size=(3, 3))
a, b, a + b, a - b, a * b, a / b, a // b, a ** b

(array([[7, 4, 8],
        [5, 7, 3],
        [7, 8, 5]], dtype=int32),
 array([[4, 8, 8],
        [3, 6, 5],
        [2, 8, 6]], dtype=int32),
 array([[11, 12, 16],
        [ 8, 13,  8],
        [ 9, 16, 11]], dtype=int32),
 array([[ 3, -4,  0],
        [ 2,  1, -2],
        [ 5,  0, -1]], dtype=int32),
 array([[28, 32, 64],
        [15, 42, 15],
        [14, 64, 30]], dtype=int32),
 array([[1.75      , 0.5       , 1.        ],
        [1.66666667, 1.16666667, 0.6       ],
        [3.5       , 1.        , 0.83333333]]),
 array([[1, 0, 1],
        [1, 1, 0],
        [3, 1, 0]], dtype=int32),
 array([[    2401,    65536, 16777216],
        [     125,   117649,      243],
        [      49, 16777216,    15625]], dtype=int32))

In [53]:
# 广播机制：对不同形状的矩阵进行运算
# 同一纬度，若相同或有一个为1，则可以进行广播
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
a, b, a + b, a - b, a * b, a / b, a // b, a ** b

(array([1, 2, 3]),
 array([[4],
        [5],
        [6]]),
 array([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]]),
 array([[-3, -2, -1],
        [-4, -3, -2],
        [-5, -4, -3]]),
 array([[ 4,  8, 12],
        [ 5, 10, 15],
        [ 6, 12, 18]]),
 array([[0.25      , 0.5       , 0.75      ],
        [0.2       , 0.4       , 0.6       ],
        [0.16666667, 0.33333333, 0.5       ]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[  1,  16,  81],
        [  1,  32, 243],
        [  1,  64, 729]]))

In [54]:
# 矩阵运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
"""
     1 2 3          4 5 6
a =  4 5 6      b = 7 8 9
     7 8 9          1 2 3
"""
a @ b  # 通过 a @ b 计算矩阵乘法

array([[ 21,  27,  33],
       [ 57,  72,  87],
       [ 93, 117, 141]])

In [126]:
np.concatenate(([1, 2, 3], [4, 5, 6]))  # np.concatenate()拼接两个ndarray

array([1, 2, 3, 4, 5, 6])

In [127]:
arr = np.random.randint(low=0, high=40, size=20)
np.split(arr, 4)  # 将ndarray平均分成n份

[array([25, 36, 25, 22,  8], dtype=int32),
 array([11,  0,  0, 33, 31], dtype=int32),
 array([24, 39,  0, 15, 38], dtype=int32),
 array([ 4, 21, 28,  2, 11], dtype=int32)]

# 基本数学函数

* 计算平方根

In [55]:
a = np.sqrt([1, 4, 9, 16])  # 返回浮点数
a, type(a)

(array([1., 2., 3., 4.]), numpy.ndarray)

* 计算指数

In [56]:
a = np.exp([0, 1, 2, 3, 4])  # 得到 e^i
a, type(a)

(array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003]),
 numpy.ndarray)

* 计算自然对数

In [57]:
a = np.log([1., 2.71828183, 7.3890561, 20.08553692, 54.59815003])  # 得到 ln(x)
a, type(a)

(array([0., 1., 2., 3., 4.]), numpy.ndarray)

* 计算三角函数

In [58]:
a = np.sin([0, np.pi / 6, np.pi / 3, np.pi / 2])
b = np.cos([0, np.pi / 6, np.pi / 3, np.pi / 2])
a, type(a), b, type(b)

(array([0.       , 0.5      , 0.8660254, 1.       ]),
 numpy.ndarray,
 array([1.00000000e+00, 8.66025404e-01, 5.00000000e-01, 6.12323400e-17]),
 numpy.ndarray)

* 计算绝对值

In [59]:
a = np.random.randint(low=-10, high=10, size=(3, 3))
a, np.abs(a)

(array([[ -9, -10,   1],
        [  1,   6,  -1],
        [  5,   4,   4]], dtype=int32),
 array([[ 9, 10,  1],
        [ 1,  6,  1],
        [ 5,  4,  4]], dtype=int32))

* 计算a的b次幂

In [60]:
a = np.array([1, 2, 3, 4])
np.power(a, 3)

array([ 1,  8, 27, 64])

* 取整（四舍五入、向上取整、向下取整）

In [61]:
a = np.random.uniform(low=-10, high=10, size=(3, 3))
a, np.round(a), np.ceil(a), np.floor(a)

(array([[ 2.36772019, -2.35076017,  9.66461772],
        [-0.66474214,  7.19880813,  3.60615077],
        [-0.99001496, -9.73470078,  8.84403511]]),
 array([[  2.,  -2.,  10.],
        [ -1.,   7.,   4.],
        [ -1., -10.,   9.]]),
 array([[ 3., -2., 10.],
        [-0.,  8.,  4.],
        [-0., -9.,  9.]]),
 array([[  2.,  -3.,   9.],
        [ -1.,   7.,   3.],
        [ -1., -10.,   8.]]))

* 检测缺失值（Nan）

In [62]:
a = np.array([1, 2, np.nan, 3])
np.isnan(a)

array([False, False,  True, False])

# 统计函数

In [63]:
arr = np.random.randint(low=1, high=20, size=(5, 5))
arr

array([[14, 18,  9,  2, 15],
       [ 7, 12,  8, 15,  3],
       [14, 17,  4, 18,  8],
       [ 4,  2,  6, 10,  4],
       [18, 12,  2, 10,  4]], dtype=int32)

* 求和

In [65]:
np.sum(arr), np.sum([1, 2, 3])

(np.int64(236), np.int64(6))

* 计算平均值

In [66]:
np.mean(arr), np.mean([1, 2, 3])

(np.float64(9.44), np.float64(2.0))

* 计算中位数

In [68]:
np.median(arr), np.median([2, 4, 8, 16, 32]), np.median([2, 4, 8, 16, 32, 64])

(np.float64(9.0), np.float64(8.0), np.float64(12.0))

* 计算标准差和方差

In [71]:
np.var(arr), np.var([1, 2, 3, 4, 5])  # 计算标准差

(np.float64(29.6864), np.float64(2.0))

In [70]:
np.std(arr), np.std([1, 2, 3, 4, 5])  # 计算方差

(np.float64(5.448522735567871), np.float64(1.4142135623730951))

* 计算最值

In [74]:
a = np.random.randint(low=1, high=200, size=(10))
a, np.max(a), np.argmax(a), np.min(a), np.argmin(a)

(array([ 14,  95,  48,  15, 190,  40,  82, 111,  53,  24], dtype=int32),
 np.int32(190),
 np.int64(4),
 np.int32(14),
 np.int64(0))

* 分位数

In [77]:
np.median(a), np.percentile(a, 50), np.percentile(a, 80)

(np.float64(50.5), np.float64(50.5), np.float64(98.2))

* 累计和、累积积

In [78]:
np.cumsum(a), np.cumprod(a)

(array([ 14, 109, 157, 172, 362, 402, 484, 595, 648, 672]),
 array([               14,              1330,             63840,
                   957600,         181944000,        7277760000,
             596776320000,    66242171520000,  3510835090560000,
        84260042173440000]))

# 比较函数

In [79]:
arr = np.random.randint(low=1, high=20, size=(10))
arr

array([13,  9, 15, 13,  1,  7,  9,  1, 12,  8], dtype=int32)

In [80]:
np.greater(arr, 10)  # 是否大于

array([ True, False,  True,  True, False, False, False, False,  True,
       False])

In [81]:
np.less(arr, 10)  # 是否小于

array([False,  True, False, False,  True,  True,  True,  True, False,
        True])

In [82]:
np.equal(arr, 15)  # 是否等于

array([False, False,  True, False, False, False, False, False, False,
       False])

In [85]:
np.logical_and([0, 1, 1, 0], [1, 1, 0, 0]), np.logical_or([0, 1, 1, 0], [1, 1, 0, 0])

(array([False,  True, False, False]), array([ True,  True,  True, False]))

In [86]:
np.any([0, 0, 0, 0, 1])  # 检查元素是否只要有一个为真

np.True_

In [87]:
np.all([0, 0, 0, 0, 1])  # 检查元素是否全部为真

np.False_

In [92]:
np.where(arr > 10, arr, 0)  # np.where(条件, 符合条件, 不符合条件)   适合分类

array([13,  0, 15, 13,  0,  0,  0,  0, 12,  0], dtype=int32)

In [105]:
np.select([arr > 12, (arr <= 12) & (arr > 8), arr <= 8], ['A', 'B', 'C'], default='?')

array(['A', 'B', 'A', 'A', 'C', 'C', 'B', 'C', 'B', 'C'], dtype='<U1')

# 排序函数

In [121]:
arr = np.random.randint(low=0, high=40, size=15)
# arr.sort()    # 通过 arr.sort() 方法排序会改变原始数组
arr

array([ 4, 38,  3,  5, 31, 29, 34, 39, 15, 12, 29, 18, 16, 18, 27],
      dtype=int32)

In [122]:
np.sort(arr), np.argsort(arr), arr  # 通过np.sort()方法排序不会改变原始数组

(array([ 3,  4,  5, 12, 15, 16, 18, 18, 27, 29, 29, 31, 34, 38, 39],
       dtype=int32),
 array([ 2,  0,  3,  9,  8, 12, 11, 13, 14,  5, 10,  4,  6,  1,  7]),
 array([ 4, 38,  3,  5, 31, 29, 34, 39, 15, 12, 29, 18, 16, 18, 27],
       dtype=int32))

In [123]:
np.unique(arr), arr  # 去重后排序

(array([ 3,  4,  5, 12, 15, 16, 18, 27, 29, 31, 34, 38, 39], dtype=int32),
 array([ 4, 38,  3,  5, 31, 29, 34, 39, 15, 12, 29, 18, 16, 18, 27],
       dtype=int32))