# 交叉熵损失函数

In [5]:
import torch
import torch.nn as nn

In [6]:
# 输入数据
input = torch.randn(3, 2)
print(input)
# 得到预测概率值
pred = torch.sigmoid(input)
print(pred)

tensor([[ 0.2093,  1.2696],
        [ 0.5759, -0.0739],
        [-0.9056, -0.7685]])
tensor([[0.5521, 0.7807],
        [0.6401, 0.4815],
        [0.2879, 0.3168]])


In [7]:
# 目标值
target = torch.tensor([[0, 1], [1, 0], [0, 1]], dtype=torch.float)
print(target)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [8]:
# 定义损失函数
loss = nn.BCELoss()
print(loss(pred, target))

tensor(0.6071)
