# 多元交叉熵损失函数

In [3]:
import torch
import torch.nn as nn

In [4]:
# 1. 目标值为顺序编码的标签
input = torch.randn(6, 8)
print(input)

pred = torch.softmax(input, dim=1)
print(pred)

tensor([[ 0.6290, -0.3621, -0.6964, -2.0892,  1.0231, -0.3341,  0.4161,  0.2759],
        [ 0.1288,  1.3708, -0.9234, -0.2191, -1.2455,  0.3550, -0.1466, -0.6105],
        [ 0.0939,  0.1267,  1.0048,  0.7983,  0.6063,  0.9539, -0.5111,  0.3175],
        [-0.6279, -1.7747,  0.4353,  0.7022, -0.5327, -0.5154,  0.2090, -2.1352],
        [ 0.8246,  0.5285, -0.4756, -0.3875,  3.3117, -0.3977,  0.1836, -1.1461],
        [-0.8357,  0.0964, -0.8593, -2.2806,  0.7944, -0.2457,  0.7480, -0.5695]])
tensor([[0.1969, 0.0731, 0.0523, 0.0130, 0.2920, 0.0752, 0.1591, 0.1383],
        [0.1210, 0.4191, 0.0423, 0.0855, 0.0306, 0.1518, 0.0919, 0.0578],
        [0.0808, 0.0835, 0.2010, 0.1635, 0.1349, 0.1910, 0.0441, 0.1011],
        [0.0785, 0.0249, 0.2272, 0.2967, 0.0863, 0.0878, 0.1812, 0.0174],
        [0.0654, 0.0486, 0.0178, 0.0194, 0.7860, 0.0193, 0.0344, 0.0091],
        [0.0561, 0.1424, 0.0547, 0.0132, 0.2861, 0.1011, 0.2732, 0.0732]])


In [5]:
# 目标值，6个数据的标签类别（0~7）
target = torch.tensor([1, 0, 3, 7, 5, 2])
print(target)

tensor([1, 0, 3, 7, 5, 2])


In [8]:
# 定义交叉熵损失函数
loss = nn.CrossEntropyLoss()
print(loss(pred, target))
print(loss(input, target))  # 不适用softmax激活，直接通过原始数据也可以计算损失函数

tensor(2.1395)
tensor(2.9077)


In [9]:
# 2. 目标值设置为独热编码（一组概率）
input = torch.randn(6, 8)
print(input)

tensor([[ 0.5190,  0.3278, -0.1533, -0.5873, -0.1110, -1.0252, -0.8683, -1.1319],
        [-0.4609, -0.7602,  0.3188,  0.8354,  0.1192, -0.1570, -0.0029, -0.1282],
        [ 1.0458,  0.4699,  0.3432,  0.2784, -0.7808, -0.2209,  0.1278, -0.1250],
        [-0.7376,  0.0293, -0.1544,  0.7509,  1.3170,  0.3862, -0.0346, -1.5703],
        [-1.7567, -0.3621,  0.0480, -2.2473, -0.0302,  0.4874,  0.4207, -1.4019],
        [ 1.6659, -1.3396, -1.7628, -0.8160, -0.0479,  0.8383,  0.9690, -1.8923]])


In [10]:
target = torch.randn(6, 8).softmax(dim=1)
print(target)

tensor([[0.0560, 0.1341, 0.0521, 0.2669, 0.0588, 0.3637, 0.0169, 0.0515],
        [0.0610, 0.0233, 0.0781, 0.1216, 0.1724, 0.1744, 0.0789, 0.2903],
        [0.2018, 0.1667, 0.0218, 0.0325, 0.3622, 0.0565, 0.0350, 0.1235],
        [0.0519, 0.2576, 0.0338, 0.1674, 0.0362, 0.3328, 0.1093, 0.0109],
        [0.0315, 0.2646, 0.1085, 0.0722, 0.0887, 0.0559, 0.3626, 0.0160],
        [0.2385, 0.0840, 0.0956, 0.0819, 0.3443, 0.0221, 0.1310, 0.0026]])


In [11]:
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.2262)
